services:
  feedback-bot:
    build: .
    container_name: feedback-bot
    restart: always
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      API_BASE_URL: ${API_BASE_URL:-http://adminpanel-back:8080/api}
      SEQ_URL: ${SEQ_URL:-}
      UPDATES_FILE_PATH: ${UPDATES_FILE_PATH:-./updates.txt}
      BROADCAST_INTERVAL_MS: ${BROADCAST_INTERVAL_MS:-60000}
    networks:
      - feedback_shared_network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  feedback_shared_network:
    external: true
