version: '3.9'

services:
  feedback-bot:
    build: .
    container_name: feedback-bot
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - OPERATOR_CHAT_ID=${OPERATOR_CHAT_ID}
      - THREAD_ID=${THREAD_ID}
      - BOT_TOKEN=${BOT_TOKEN}
    restart: always